### PR TITLE
index restructured and added notebooks for geocamp es workshops

### PR DESCRIPTION
**Pull request by jsanz**
I added last [geocampes 2017](http://2017.geocamp.es) couple notebooks I created about Python SDK and CARTO Frames. I also changed links to point to `nbviewer` which is nicer than default github rendering.

### CODE REVIEW

**Comment by jsanz** [comment]
@oriolbx you can check the notebooks I created for the [python sdk](https://nbviewer.jupyter.org/github/jsanz/geocampes17/blob/master/carto/CARTO%20Python%20SDK%20workshop.ipynb) and [cartoframes](https://nbviewer.jupyter.org/github/jsanz/geocampes17/blob/master/carto/CARTO%20Frames%20workshop.ipynb) as I haven't changed anything.

I decided not to :hocho: your workshop but maybe we can just remove it from the index, let me know what you think

**Comment by oriolbx** [comment]
@jsanz LGTM  :)

 But, It looks like the URL's for the for nbviewer notebooks of new introduction to CARTO-python and CARTO Frames of carto-workshop are not been found. I guess that after pushing the commits to GitHub, they will appear on the nbviewer

**Comment by jsanz** [comment]
Pues for some reason they don't work but I guess is that it needs some time to appear in a CDN or something, I'll review this tomorrow.

Thanks for the review!

**Comment by jsanz** [comment]
Now they work :man_shrugging:

**Pull request merged**
